apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:8.0.40
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: ${MYSQL_PASSWORD}
            - name: MYSQL_DATABASE
              value: ${MYSQL_DATABASE}
            - name: MYSQL_USER
              value: ${MYSQL_USER}
            - name: MYSQL_PASSWORD
              value: ${MYSQL_PASSWORD}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc  # Ensure you have a PVC for persistent storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None


apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
        - name: django-app
          image: temz/alx_msg_app:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: ${MYSQL_HOST}
            - name: MYSQL_DB
              value: ${MYSQL_DATABASE}
            - name: MYSQL_USER
              value: ${MYSQL_USER}
            - name: MYSQL_PASSWORD
              value: ${MYSQL_PASSWORD}
            - name: SECRET_KEY
              value: ${SECRET_KEY}
            - name: DEBUG
              value: ${DEBUG}
            - name: USE_MYSQL
              value: ${USE_MYSQL}
            - name: MYSQL_PORT
              value: ${MYSQL_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  clusterIP: None
