services:
  db:
    image: mysql:8.0.40
    container_name: messaging_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_app_server
    command: python3 manage.py runserver 0.0.0.0:8000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

    environment:
      - USE_MYSQL=True
      - MYSQL_DB=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

volumes:
  mysql_data:
